version: '3'
services:

  jupyter:
    build:
      context: .
    ports:
       - "127.0.0.1::8888"
    volumes:
       - ../:/mnt
    entrypoint: bash -c "cd /mnt && jupyter notebook --NotebookApp.token='' --ip=0.0.0.0 --allow-root && /bin/bash" 
    stdin_open: true
    container_name: "merf_jupyter_${USER}"
    tty: true
